### PR TITLE
Adding support for HTML entities for HTML docs only

### PR DESCRIPTION
**Pull request by kethinov**
Closes https://github.com/jindw/xmldom/pull/58.

This is based on @andromedado's PR but limits the scope of the changes to only HTML documents as only lt, gt, amp, quot, and apos are defined in XML (http://en.wikipedia.org/wiki/Character_entity_reference), as correctly pointed out by @youngj.

### CODE REVIEW

**Comment by codler** [comment]
Great! I hope it will get released to npm soon!

**Comment by rduenasf** [comment]
@kethinov @jindw do you guys are planning to release this at some point?

**Comment by kethinov** [comment]
I have push powers for npm, but I don't have push powers to the GitHub repo, so I can't issue a npm release until the version number gets bumped. @jindw will have to do it.

**Comment by jindw** [comment]
fixed and published as xmldom-alpha
thanks


DOMParser.prototype.parseFromString = function(source,mimeType){

...

   var isHTML = /\/x?html?$/.test(mimeType);
//mimeType.toLowerCase().indexOf('html') > -1;

  var entityMap = isHTML?htmlEntity.entityMap:{'lt':'<','gt':'>','amp':'&',
'quot':'"','apos':"'"};


2017-05-06 7:12 GMT+08:00 Eric Newport <notifications@github.com>:

**Pull request merged**
