### PR TITLE
Expose the entityMap variable to allow configuration.

### PR DESCRIPTION
**Pull request by nathanhinish**
Sometimes it may be desirable to convert a different set of entities or none at all. This would allow the entity set to be configurable.

### CODE REVIEW

**Comment by m0nzderr** [comment]
+1. This feature is absolutely necessary to handle custom entities.

**Comment by dcrockwell** [comment]
+1

**Comment by nathanhinish** [comment]
@dcrockwell The variable is only available within the DOMParser.js file...not globally.

**Comment by dcrockwell** [comment]
@nathanhinish Ah, I see. Thanks! +2

**Comment by codler** [comment]
Fixed by #80

**Comment by retorquere** [comment]
#80 doesn't really address the current issue; it seems to extend the entitymap for html, but does not allow me to specify my own (pre-parsed from a DTD).

**Pull request closed without merging**
